### ISSUE TITLE
Make Renderer use different image dimensions for items and mobs.

### ISSUE THREAD

**Issue by FindMeSomeFun** [D-Cysteine/nesql-exporter#7]
Mob images are larger then item icons, but Renderer is instantiated once with item icon size so it uses that size for rendering all images.
We need Renderer to change image size depending on job type.

Maybe we could separate icon and mob image rendering so we can render all icons separately with icon size and then with new renderer for mobs image size.

**Comment by D-Cysteine** [comment]
Implemented in https://github.com/D-Cysteine/nesql-exporter/commit/6300d7f738f78ad1852517da56494f796dccc14a
